name: Build Wheels

on: [push, pull_request]

jobs:
  build_binaries:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Cancel previous runs on the same branch
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest
      - name: Check cmake
        run: |
          cmake --version
          mkdir -p build && cd build
          cmake ../
          cmake --build . -- -j 6
          ls -la
