name: Build Binaries

on: [push, pull_request]

jobs:
  deploy:
    name: Deploy
    needs: build_binaries
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: |
          mv artifacts/posp-ubuntu-20.04/ProofOfSpace ./posp_bin_linux-amd64
          rm -fr artifacts/posp-ubuntu-20.04
          mv artifacts/posp-macos-latest/ProofOfSpace ./posp_bin_darwin-amd64
          rm -fr artifacts/posp-macos-latest
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            posp_bin_linux-amd64
            posp_bin_darwin-amd64
  build_binaries:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
    steps:
      - name: Cancel previous runs on the same branch
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest
      - name: Build binary
        run: |
          cmake --version
          mkdir -p build && cd build
          cmake ../
          cmake --build . -- -j 6
      - uses: actions/upload-artifact@v2
        with:
          name: posp-${{ matrix.os }}
          path: build/ProofOfSpace
          if-no-files-found: error
