name: Release Binaries
on: [push, pull_request]
deploy:
  name: Deploy
  needs: build_binaries
  runs-on: ubuntu-20.04
  steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
    - name: Display structure of downloaded files
      run: ls -R
